# Generated by Django 5.0 on 2023-12-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_exp_event_content_date_content_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
