# Generated by Django 5.0 on 2023-12-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_exp_securityanswer_exp_securityquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exp',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
